---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meg-app
  labels:
    app: meg-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meg-app
  template:
    metadata:
      labels:
        app: meg-app
    spec:
      containers:
        - name: meg-container
          image: 043509840958.dkr.ecr.ap-southeast-2.amazonaws.com/amazon-prime:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
...