---
apiVersion: v1
kind: Service
metadata:
  name: meg-app
  labels:
    app: meg-app
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: pandacloud-app
  type: LoadBalancer
...
